# Generated by Django 4.2.3 on 2023-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('valorCusto', models.FloatField(verbose_name='Valor de custo')),
                ('margemCusto', models.FloatField(verbose_name='Margem do produto')),
                ('valorVenda', models.FloatField(verbose_name='Valor de venda')),
            ],
        ),
    ]
