# Generated by Django 4.2.3 on 2023-07-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valorVenda',
            field=models.FloatField(null=True, verbose_name='Valor de venda'),
        ),
    ]
