# Generated by Django 4.2.3 on 2023-07-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_valorvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valorVenda',
            field=models.FloatField(verbose_name='Valor de venda'),
        ),
    ]
