# Generated by Django 4.2.3 on 2023-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_margemcusto_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='margemCusto',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margem de lucro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorCusto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valorVenda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de venda'),
        ),
    ]
