# Generated by Django 4.2.3 on 2023-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('descricao', models.CharField(max_length=15, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('dataTrans', models.DateField(null=True, verbose_name='Data da transação')),
                ('valorTotalDiario', models.FloatField(default=0.0, verbose_name='Valor Total Diário')),
                ('valorTotalMensal', models.FloatField(default=0.0, verbose_name='Valor Total Mensal')),
            ],
        ),
    ]
