# Generated by Django 4.2.3 on 2023-07-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacoes',
            name='valorTotalDiario',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='valorTotalMensal',
        ),
    ]
