# Generated by Django 4.2.3 on 2023-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_remove_transacoes_valortotaldiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='valorTotalDiario',
            field=models.FloatField(default=0.0, verbose_name='Valor Total Diário'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='valorTotalMensal',
            field=models.FloatField(default=0.0, verbose_name='Valor Total Mensal'),
        ),
    ]
