# Generated by Django 4.2.3 on 2023-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('rg', models.CharField(max_length=20, null=True)),
                ('cidade', models.CharField(max_length=25)),
                ('telefone', models.CharField(max_length=20)),
                ('numero', models.IntegerField(max_length=5)),
                ('rua', models.CharField(max_length=60, null=True)),
                ('bairro', models.CharField(max_length=20)),
            ],
        ),
    ]
