# Generated by Django 4.2.3 on 2023-07-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arquivos.registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
