# Generated by Django 4.2.3 on 2023-08-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email_alter_cliente_rg_and_more'),
        ('arquivos', '0002_alter_item_registro_alter_registro_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
