# Generated by Django 4.2.3 on 2023-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_item_valorprod_alter_registro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Número residencial'),
        ),
    ]
