# Generated by Django 4.2.3 on 2023-08-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0005_alter_registro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='bairro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cidade',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número residencial'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rua',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
