# Generated by Django 4.2.3 on 2023-08-08 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0007_alter_registro_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data do registro'),
        ),
    ]
