# Generated by Django 4.2.3 on 2023-08-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0009_registro_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valorProd',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_total',
            field=models.FloatField(default=0, verbose_name=''),
        ),
    ]
