# Generated by Django 4.2.3 on 2023-08-09 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0011_alter_registro_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Pedido'), ('O', 'Orçamento')], max_length=1),
        ),
    ]
