# Generated by Django 4.2.3 on 2023-08-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0013_alter_registro_data_alter_registro_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valorProd',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_total',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
