# Generated by Django 4.2.3 on 2023-08-09 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('arquivos', '0014_alter_item_quantidade_alter_item_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
    ]
