# Generated by Django 4.2.3 on 2023-08-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0019_alter_item_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
    ]
