# Generated by Django 4.2.3 on 2023-08-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0021_alter_item_quantidade_alter_item_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valorProd',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name=''),
        ),
    ]
