# Generated by Django 4.2.3 on 2023-08-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0022_alter_item_quantidade_alter_item_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
    ]
