# Generated by Django 4.2.3 on 2023-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0023_alter_item_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='valor_total',
            new_name='totalProd',
        ),
    ]
