# Generated by Django 4.2.3 on 2023-08-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0024_rename_valor_total_item_totalprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Pedido'), ('O', 'Orçamento')], max_length=1, null=True),
        ),
    ]
