# Generated by Django 4.2.3 on 2023-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0025_alter_registro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo',
            field=models.CharField(choices=[('P', 'Pedido'), ('O', 'Orçamento')], max_length=1),
        ),
    ]
