# Generated by Django 4.2.3 on 2023-08-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0026_alter_registro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='vendedor',
            field=models.CharField(max_length=15),
        ),
    ]
