# Generated by Django 4.2.3 on 2023-08-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0027_alter_registro_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='vendedor',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
