# Generated by Django 4.2.3 on 2023-08-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0028_alter_registro_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=''),
        ),
    ]
