# Generated by Django 4.2.3 on 2023-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0029_alter_item_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='totalPedido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
